apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
spec:
  selector:
    app: getting-started
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
spec:
  replicas: 4
  selector:
    matchLabels:
      service: getting-started-service
  template:
    metadata:
      labels:
        app: getting-started
        service: getting-started-service
    spec:
      containers:
      - name: getting-started
        image: getting-started:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
